openapi: 3.0.0
info:
  title: Share Secret API
  description: API for creating secrets and share them
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /secret/{id}:
    get:
      summary: Show a secret by ID
      description: Returns content decrypt by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the secret to show
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveSecretResponse'
        '404':
          description: Secret not found or already read
          content: {}
components:
  schemas:
    RetrieveSecretResponse:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          description: Content decrypt
