version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: berni
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: sharesecret

    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql"