version: '3.1'
services:
  web:
    build: .
    environment:
      SERVER_PORT: 8080
      SERVER_URL: http://127.0.0.1
      SECRET_KEY: 11111111111111111111111111111111
      SECRET_PASSWORD: "@myPassword"
      DB_NAME: sharesecret
      DB_USER: berni
      DB_PASS: 1234
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - 8080:8080
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: berni
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: sharesecret

    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"